---
- name: Check if docker is installed and started
  shell: "systemctl is-active {{ docker_service_name }} | grep ^active -c | cat"
  register: docker_is_active

- name: Ensure config directory for docker service is present
  file:
    path: "{{ docker_service_config_dir }}"
    state: directory

- name: Ensure proxy is set for docker
  copy:
    content: |
      [Service]
      Environment="HTTP_PROXY={{ proxy_url }}"
    dest: "{{ docker_service_config_dir }}/{{ docker_service_proxy_config_file }}"
  notify:
    - restart docker
